### ISSUE TITLE
Minor: Update link in README.md

### ISSUE THREAD

**Issue by swxrob** [monte-flora/scikit-explain#24]
In README.md, the following embedded documentation link goes to a dead end. Here's the context:

"The computations do leverage parallelization when possible. Documentation for scikit-explain can be found at https://scikit-explain.readthedocs.io/en/master/."

**Comment by monte-flora** [comment]
Thank you for pointing that out as I found the readthedocs page was also outdated. I've recently updated the readthedocs to include the tutorial notebooks as additional documentation.
