### ISSUE TITLE
Pickle file `tutorial_data/multipass_importance_naupdc.nc` not readable?

### ISSUE THREAD

**Issue by jvpeetz** [monte-flora/scikit-explain#33]
Again, thanks for doing this project, now under a new flag :-)
Trying the notebooks `accumulated_local_effect_tutorial.ipynb` and `feature_contributions.ipynb`, the pickle file `tutorial_data/multipass_importance_naupdc.nc` could not be read. The traceback ended with:
```
  src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()
  src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._get_vars()
  src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()
  RuntimeError: NetCDF: HDF error
```
The following versions for the underlying Python modules were used:

- Python: 3.9.13
- scikit-explain: 0.0.7
- xarray: 0.16.1
- netCDF4: 1.5.7

Any idea?
Regards, Jörg.

**Comment by monte-flora** [comment]
The file is a netCDF4 file, not a pickle file. I'm not sure of the error source, but the file is generated by [permutation_importance_tutorial.ipynb](https://github.com/monte-flora/scikit-explain/blob/master/tutorial_notebooks/permutation_importance_tutorial.ipynb). Can you run that notebook and then re-try to load the file in one of the notebooks you listed above?

**Comment by jvpeetz** [comment]
Thank you very much for suggesting your notebook `permutation_importance_tutorial.ipynb`. It also can't read in the just written netCDF4 file.
Therefore I did a few experiments:
a file written directly without encoding can be read in again, the following works after cell 5:
```
myfn = 'multipass_importance_naupdc.nc'
results.to_netcdf(myfn)
results.close()
explainer = skexplain.ExplainToolkit()
results = explainer.load(fnames=myfn)
```
This, anyhow, allows to generate working input files for the other notebooks.
Maybe, it's an error in the xarray package I'm using. I'm working on a Linux Debian System and the package is named `python3-xarray` in version 2022.06.0-1. At least  with a small Dataset, I couldn't reproduce the error. The following worked in ipython3:
```
import numpy as np
import pandas as pd
import xarray as xr

np.random.seed(0)
temperature = 15 + 8 * np.random.randn(2, 2, 3)
precipitation = 10 * np.random.rand(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
time = pd.date_range("2014-09-06", periods=3)
reference_time = pd.Timestamp("2014-09-05")

ds = xr.Dataset(
    data_vars=dict(
        temperature=(["x", "y", "time"], temperature),
        precipitation=(["x", "y", "time"], precipitation),
    ),
    coords=dict(
        lon=(["x", "y"], lon),
        lat=(["x", "y"], lat),
        time=time,
        reference_time=reference_time,
    ),
    attrs=dict(description="Weather related data."),
)
ds

fname = 'xarray-ex-1.nc'
comp = dict(zlib=True, complevel=5)
encoding = {var: comp for var in ds.data_vars}
ds.to_netcdf(path=fname, encoding=encoding)
ds.close()

dsin = xr.open_dataset(fname)

dsin
```
Regards,
Jörg.

**Comment by monte-flora** [comment]
Thanks for testing it out. I may remove the encoding in the `save_netcdf` code in `skexplain.common.io`.  Given the cause of the issue is unknown, I'll leave the issue open.

**Comment by jvpeetz** [comment]
In the notebook `partial_dependence_tutorial.ipynb` I tried to store the multidimensional Dataset `hstat_results` to a file with the `to_netcdf()` method. For me it only worked by setting the additional parameter `engine='h5netcdf'`. Maybe, this should also be used in `skexplain.common.io`?
Regards, Jörg.

**Comment by monte-flora** [comment]
I'll look further into this. You should just need to install the python package` netCDF4` and be able to load the dataset.

**Comment by monte-flora** [comment]
In the README under Dependencies I've noted that the user will have to install netCDF4. I've also generalized the save function to allow users to pass keyword args. You should be able to pass engine='h5netcdf' from the save command now.
