### ISSUE TITLE
Typo in common/multiprocessing_utils.py line 156

### ISSUE THREAD

**Issue by jvpeetz** [monte-flora/scikit-explain#48]
Hi,
there's an error in file `common/multiprocessing_utils.py` in line 156, obviously you wanted to type `mp.cpu_count()` instead of `np.cpu_count()`. I found it when trying your notebook `accumulated_local_effect_tutorial.ipynb`.
Many thanks for the upgrade. By the way, the version number of the PyPi packet is incorrectly set to 0.0.5.
Regards,
Jörg.

**Comment by monte-flora** [comment]
Thanks for the catch! I've fixed the typo. and where is the version number set to 0.0.5?

**Comment by jvpeetz** [comment]
After installing via PyPi, i.e.,
```
python3 -m pip install scikit-explain
```
the version number is set wrong in `skexplain/__init__.py`: `__version__ = '0.0.5'`

It seems, the error is in in the git repo in `skexplain/__init__.py`.

Regards,
Jörg.

**Comment by monte-flora** [comment]
I've updated that the version number in that file.
