### ISSUE TITLE
I do not want to show "(a)"  in figure, what should i do?

### ISSUE THREAD

**Issue by 1209098482** [monte-flora/scikit-explain#54]
![微信图片_20230503215022](https://user-images.githubusercontent.com/31590080/235935882-6a1476ce-f57a-4160-b9ff-4f64cd3f3e5e.png)

**Comment by monte-flora** [comment]
Thanks for raising this issue! By default, scikit-explain is built for scientific publications and will provide figure labels (e.g.,  the (a) in the lower right). To avoid this, you can provide your own matplotlib Axes object as an argument.  I've added the following to the [ALE tutorial notebook](https://github.com/monte-flora/scikit-explain/blob/master/tutorial_notebooks/accumulated_local_effect_tutorial.ipynb) to demonstrate this: 

```python 
import matplotlib.pyplot as plt 

fig, ax = plt.subplots(dpi=150)
fig, ax = explainer.plot_ale(
                                   ale = ale_1d_ds, 
                                   features='dwpt2m',
                                   display_units=plotting_config.display_units,
                                   display_feature_names=plotting_config.display_feature_names,
                                    ax=ax
                                  )
```

**Comment by 1209098482** [comment]
> Thanks for raising this issue! By default, scikit-explain is built for scientific publications and will provide figure labels (e.g., the (a) in the lower right). To avoid this, you can provide your own matplotlib Axes object as an argument. I've added the following to the [ALE tutorial notebook](https://github.com/monte-flora/scikit-explain/blob/master/tutorial_notebooks/accumulated_local_effect_tutorial.ipynb) to demonstrate this:
> 
> ```python
> import matplotlib.pyplot as plt 
> 
> fig, ax = plt.subplots(dpi=150)
> fig, ax = explainer.plot_ale(
>                                    ale = ale_1d_ds, 
>                                    features='dwpt2m',
>                                    display_units=plotting_config.display_units,
>                                    display_feature_names=plotting_config.display_feature_names,
>                                     ax=ax
>                                   )
> ```
> 
> ![image](https://user-images.githubusercontent.com/56733346/235941731-269757ae-7668-4978-b049-d464f7fdfc0e.png)

Thanks for your answer, but ModuleNotFoundError: No module named 'plotting_config'

**Comment by monte-flora** [comment]
I am closing this comment. If you run into additional issues, feel free to raise another.
