### ISSUE TITLE
Dear author, I do not want to show these point, what should i do? Thank you!

### ISSUE THREAD

**Issue by 1209098482** [monte-flora/scikit-explain#56]
![微信截图_20230504173738](https://user-images.githubusercontent.com/31590080/236168356-21c5419b-df36-4ba3-8f8d-48824dcb94ef.png)

**Comment by monte-flora** [comment]
Sorry for not providing documentation on this. You can remove the scatter plots by adding `scatter=False` to the plotting function: 
```python 
fig, axes = explainer.plot_ale(ale=ale_2d_ds,
                               scatter= False
                                  )
```
I've added that information to the documentation and [tutorial notebooks](https://github.com/monte-flora/scikit-explain/blob/master/tutorial_notebooks/accumulated_local_effect_tutorial.ipynb). You can also turn off the KDE curves and convert the pixel-style image to a smoothed filled contour.

**Comment by monte-flora** [comment]
I am closing this comment. If you have additional issues, feel free to raise them.
