### ISSUE TITLE
Using on our own matplotlib Axes object for "plot_importance"

### ISSUE THREAD

**Issue by mammadha** [monte-flora/scikit-explain#57]
Hi, 

My own axis object does not work for plotting "permutation_importance". 

It works for ALE as explained in the tutorial but not for importance. 

I think there is not any "ax" argument for "plot_importance". Am I right? What can I do so? 

Thank you very much,
Mohammad

**Comment by monte-flora** [comment]
Yes, there was no "ax" argument for the plot_importance function. I've added that functionality, which is available in the most recent upload (in the minor_updates branch). I've started a pull request and should be uploading a new version to PyPi tomorrow or sometime next week.

**Comment by monte-flora** [comment]
Actually, went ahead and performed the pull request, so the changes are available on the main branch now.

**Comment by mammadha** [comment]
Thank you very much for your quick help! 

I also have a problem with the "2D Partial Dependence" plot. 

Why do the color bar numbers appear this way (the top right panel)? Is it related to my data?
How can I control the color bar properties? 

![PD_2D](https://github.com/monte-flora/scikit-explain/assets/101438927/9afe9c27-b8fb-44e4-b2c2-d7e3afa80218)

I really appreciate your time. 
Mohammad

**Comment by monte-flora** [comment]
Okay, I've modified the code for a `cbar_kwargs` arg for plot_ale or plot_pd and in that dict, you set up matplotlib colorbar (https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html) args. You can see this demonstrated in the updated ALE tutorial notebooks (same for PD; ) under the "Customizing the colobar, figure size, font size, and number of bins in the histograms". As the title suggests, I've also added additional flexibility. For example, setting a different figure size will improve the aspect ratio of the plot and improve the appearance of the colorbar. Here is a similar figure I made with the new code: 
![image](https://github.com/monte-flora/scikit-explain/assets/56733346/2ff11f32-6d42-40ec-9e38-2265ee7f081b)

Hope that helps! Let me know if you run into any other issues.

**Comment by mammadha** [comment]
Thank you very much! 

Your kind help is really appreciated!

**Comment by mammadha** [comment]
> Actually, went ahead and performed the pull request, so the changes are available on the main branch now.

Hi again, 

Sorry for bothering you. I am a bit amateur at using codes from Git Hub. You mentioned that the changes are available on the main branch, but I did not understand it.
I removed and reinstall the scikit-explain package on my PyCharm but I still do not have the "ax" feature. 
Should I change the source code myself? 

Thank you very much for your time,
Mohammad

**Comment by monte-flora** [comment]
No problem. If you have access to a command line, You'll need to clone the repo (`git clone https://github.com/monte-flora/scikit-explain`) and then change to the scikit-explain `(cd scikit-explain)` directory and run the command `python setup.py install`. This will allow you to install updates from the source code rather than waiting for PyPi/Conda to update. Since other like yourself may not be familiar with that option, I've added those commands to README for the github page.

**Comment by mammadha** [comment]
> No problem. If you have access to a command line, You'll need to clone the repo (`git clone https://github.com/monte-flora/scikit-explain`) and then change to the scikit-explain `(cd scikit-explain)` directory and run the command `python setup.py install`. This will allow you to install updates from the source code rather than waiting for PyPi/Conda to update. Since other like yourself may not be familiar with that option, I've added those commands to README for the github page.

Thank you very much for your response. 
I really appreciate your time.
